version: '3.8'

services:
  express-app:
    build: 
      context: . 
      dockerfile: js_server/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./js_server:/app/js_server:delegated
      - ./views:/app/views:delegated
      - ./public:/app/public:delegated
      - /app/js_server/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/mydatabase

  django-app:
    build: 
      context: . 
      dockerfile: python_server/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./python_server:/app/python_server:delegated
      - ./views:/app/views:delegated
      - ./public:/app/public:delegated
      - /app/python_server/venv
    env_file:
      - .env
    environment:
      - DATABASE_HOST=postgres
    
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:latest
    # environment:
    #   POSTGRES_DB: "${POSTGRES_DB}"
    #   POSTGRES_USER: "${POSTGRES_USER}"
    #   POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  postgres-data:
