# Generated by Django 5.0.7 on 2024-07-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('data', models.BinaryField()),
                ('contentType', models.CharField(max_length=50)),
                ('attributes', models.TextField()),
            ],
        ),
    ]
