# Generated by Django 5.0.7 on 2024-08-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gif_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='attributes',
            field=models.JSONField(),
        ),
    ]
