# Generated by Django 5.0.7 on 2024-08-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gif_service', '0002_alter_gif_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='data',
            field=models.FileField(upload_to='gifs/'),
        ),
    ]
