# Generated by Django 5.0.7 on 2024-08-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gif_service', '0003_alter_gif_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='data',
            field=models.BinaryField(),
        ),
    ]
